name: flet_zxing
description: Flet Zxing control
repository: https://github.com/usermicrodevices/fletzxing/src/flutter/flet_zxing
version: 0.0.1
homepage: https://github.com/usermicrodevices/fletzxing

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: 0.27.6
  flutter:
    sdk: flutter
  flutter_zxing: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
